name: Docker Image CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Prepare repository
      run: git fetch --unshallow --tags
    - name: Poetry Build
      run: |
        DOCKER_BUILDKIT=0 docker build -t python-dotjson:build --progress=plain .
