name: Docker Image CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Prepare repository
      run: git fetch --unshallow --tags
    - name: Poetry Build
      run: |
        DOCKER_BUILDKIT=0 docker build -t python-dotjson:build --progress=plain \
        --build-arg RUN_TESTS=y .
    - name: Extract Code Coverage
      run: |
        export CONTAINER_ID="$(docker run -dit --entrypoint bash python-dotjson:build)"
        echo "CONTAINER_ID: $CONTAINER_ID"
        mkdir report
        docker cp "${CONTAINER_ID}:/project/pytest-coverage.txt" ./
        docker stop $CONTAINER_ID 
        docker container rm $CONTAINER_ID
        echo "Test coverage file extracted"
        cat /project/pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2