name: Docker Image CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Force Install GIT latest
      run: |
          apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && apt-get install -y git
    - uses: actions/checkout@v2
    - run: |
        ls
    - name: Poetry Build
      run: |
        DOCKER_BUILDKIT=0 docker build -t python-dotjson:build --progress=plain .
