name: Docker Image CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: aakashkhanna/python-dotjson
        fetch-depth: 0
    - run: |
        ls
    - name: Poetry Build
      run: |
        DOCKER_BUILDKIT=0 docker build -t python-dotjson:build --progress=plain .
