name: Docker Image CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare repository
      run: git fetch --unshallow --tags
    - run: |
        DOCKER_BUILDKIT=0 docker build -t python-dotjson:build --progress=plain\
        --build-arg POETRY_PYPI_TOKEN_PYPI=${{ secrets.POETRY_PYPI_TOKEN_PYPI }}\
        --build-arg PUBLISH=y .
